services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    init: true
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL}
        - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
        - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}
        - JWT_SECRET=${JWT_SECRET}
        - IMG_S=${IMG_S}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: