services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    init: true
    depends_on: []
    # env_file: ./.env  # Uncomment if .env file exists
networks:
  default: